# Generated by Django 5.2.4 on 2026-10-05 11:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("manager", "Manager"), ("employee", "Employé")],
                        default="employee",
                        max_length=10,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Compte actif"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vide pour le propriétaire du SaaS (accès à l'admin uniquement).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="accounts.account",
                        verbose_name="Compte client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        help_text="Boutique de l'employé (le gérant voit toutes les boutiques).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="accounts.shop",
                        verbose_name="Boutique",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Stock sous lequel un produit est considéré en stock faible",
                        verbose_name="Seuil d'alerte stock",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nom commercial affiché sur les factures et l'interface",
                        max_length=150,
                        verbose_name="Nom de l'entreprise",
                    ),
                ),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True,
                        help_text="Image du logo (PNG/JPG). Affichée sur les factures et l'interface",
                        null=True,
                        upload_to="logos/",
                        verbose_name="Logo de l'entreprise",
                    ),
                ),
                (
                    "company_tagline",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Court descriptif affiché sous le nom sur les factures (max 80 car.). Ex: Boutique de vêtements, Restaurant, etc.",
                        max_length=80,
                        verbose_name="Slogan / Activité",
                    ),
                ),
                (
                    "brand_color_primary",
                    models.CharField(
                        default="#3d35e6",
                        help_text="Couleur principale de l'entreprise (titres, barres)",
                        max_length=7,
                        verbose_name="Couleur principale",
                    ),
                ),
                (
                    "brand_color_secondary",
                    models.CharField(
                        default="#198754",
                        help_text="Couleur secondaire (accents, montants payés)",
                        max_length=7,
                        verbose_name="Couleur secondaire",
                    ),
                ),
                (
                    "brand_color_accent",
                    models.CharField(
                        default="#dc3545",
                        help_text="Couleur d'accent (alertes, montants restants)",
                        max_length=7,
                        verbose_name="Couleur d'accent",
                    ),
                ),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image de signature manuscrite (PNG fond transparent recommandé)",
                        null=True,
                        upload_to="signatures/",
                        verbose_name="Signature du responsable",
                    ),
                ),
                (
                    "stamp_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image du cachet d'entreprise (PNG fond transparent recommandé)",
                        null=True,
                        upload_to="stamps/",
                        verbose_name="Cachet / Tampon",
                    ),
                ),
                (
                    "signatory_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nom + titre affichés sous la signature. Ex: Aliou Diallo - Gérant",
                        max_length=100,
                        verbose_name="Nom du signataire",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_settings",
                        to="accounts.account",
                        verbose_name="Compte client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètre de l'application",
                "verbose_name_plural": "Paramètres de l'application",
            },
        ),
        migrations.CreateModel(
            name="PasswordResetCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reset_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Code de réinitialisation",
                "verbose_name_plural": "Codes de réinitialisation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Adresse"),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'embauche"
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Salaire",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil utilisateur",
                "verbose_name_plural": "Profils utilisateurs",
            },
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "manager")),
                fields=("account",),
                name="user_single_manager_per_account",
            ),
        ),
    ]
