# Generated by Django 5.2.4 on 2026-04-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='brand_color_accent',
            field=models.CharField(default='#dc3545', help_text="Couleur d'accent (alertes, montants restants)", max_length=7, verbose_name="Couleur d'accent"),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='brand_color_primary',
            field=models.CharField(default='#2c5aa0', help_text="Couleur principale de l'entreprise (titres, barres)", max_length=7, verbose_name='Couleur principale'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='brand_color_secondary',
            field=models.CharField(default='#198754', help_text='Couleur secondaire (accents, montants payés)', max_length=7, verbose_name='Couleur secondaire'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='company_tagline',
            field=models.CharField(blank=True, default='', help_text='Court descriptif affiché sous le nom sur les factures (max 80 car.). Ex: Boutique de vêtements, Restaurant, etc.', max_length=80, verbose_name='Slogan / Activité'),
        ),
    ]
