# Generated by Django 5.2.4 on 2026-10-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswordResetCode",
        ),
    ]
