# Generated by Django 5.2.4 on 2026-04-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appsetting_brand_color_accent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='signatory_name',
            field=models.CharField(blank=True, default='', help_text='Nom + titre affichés sous la signature. Ex: Aliou Diallo - Gérant', max_length=100, verbose_name='Nom du signataire'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Image de signature manuscrite (PNG fond transparent recommandé)', null=True, upload_to='signatures/', verbose_name='Signature du responsable'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='stamp_image',
            field=models.ImageField(blank=True, help_text="Image du cachet d'entreprise (PNG fond transparent recommandé)", null=True, upload_to='stamps/', verbose_name='Cachet / Tampon'),
        ),
    ]
