# Generated by Django 5.2.4 on 2026-10-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_passwordresetcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appsetting",
            name="brand_color_primary",
            field=models.CharField(
                default="#3d35e6",
                help_text="Couleur principale de l'entreprise (titres, barres)",
                max_length=7,
                verbose_name="Couleur principale",
            ),
        ),
    ]
