# Generated by Django 5.2.4 on 2026-10-05 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("users", "0005_brand_color_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsetting",
            name="account",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="app_settings",
                to="accounts.account",
                verbose_name="Compte client",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Vide pour le propriétaire du SaaS (accès à l'admin uniquement).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="accounts.account",
                verbose_name="Compte client",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                help_text="Boutique de l'employé (le gérant voit toutes les boutiques).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="accounts.shop",
                verbose_name="Boutique",
            ),
        ),
        migrations.AlterField(
            model_name="appsetting",
            name="currency_label",
            field=models.CharField(default="GMD", max_length=10),
        ),
    ]
