# Generated by Django 5.2.4 on 2026-10-05 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_legacy_data"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0006_saas_1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appsetting",
            name="currency_label",
        ),
        migrations.AlterField(
            model_name="appsetting",
            name="account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="app_settings",
                to="accounts.account",
                verbose_name="Compte client",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "manager")),
                fields=("account",),
                name="user_single_manager_per_account",
            ),
        ),
    ]
