# Generated by Django 5.2.4 on 2026-10-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_sync_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["name"],
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(
                help_text="Numéro de téléphone (unique)", max_length=20, unique=True
            ),
        ),
    ]
