# Generated by Django 5.2.4 on 2026-10-05 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("client", "0003_alter_client_options_alter_client_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="shop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="accounts.shop",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(
                help_text="Numéro de téléphone (unique dans la boutique)", max_length=20
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                fields=("shop", "phone"), name="client_unique_phone_per_shop"
            ),
        ),
    ]
