# Generated by Django 5.2.4 on 2026-10-05 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Entreprise")),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("GN", "Guinée"),
                            ("GM", "Gambie"),
                            ("SN", "Sénégal"),
                            ("ML", "Mali"),
                            ("CI", "Côte d'Ivoire"),
                            ("GW", "Guinée-Bissau"),
                            ("SL", "Sierra Leone"),
                            ("LR", "Liberia"),
                            ("MR", "Mauritanie"),
                        ],
                        max_length=2,
                        verbose_name="Pays",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        help_text="Affichée sur tous les montants (ex : GNF, GMD, XOF).",
                        max_length=10,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Décoché : personne du compte ne peut se connecter.",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "active_until",
                    models.DateField(
                        blank=True,
                        help_text="Dernier jour d'accès inclus. Vide : sans date de fin.",
                        null=True,
                        verbose_name="Actif jusqu'au",
                    ),
                ),
                (
                    "max_shops",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Boutiques autorisées"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Visible uniquement dans l'admin (paiements reçus, contact…).",
                        verbose_name="Notes internes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Inscrit le"),
                ),
            ],
            options={
                "verbose_name": "Compte client",
                "verbose_name_plural": "Comptes clients",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("max_shops__gte", 1)),
                        name="account_max_shops_gte_1",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(
                        help_text="2 à 6 lettres ou chiffres, en tête des numéros de vente (ex : KAL-000123).",
                        max_length=6,
                        verbose_name="Code",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Adresse"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "next_number",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        verbose_name="Dernier numéro de vente",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to="accounts.account",
                        verbose_name="Compte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boutique",
                "verbose_name_plural": "Boutiques",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "code"), name="shop_unique_code_per_account"
                    ),
                    models.UniqueConstraint(
                        fields=("account", "name"), name="shop_unique_name_per_account"
                    ),
                ],
            },
        ),
    ]
