# Generated by Django 5.2.4 on 2026-10-02 15:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_sync_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["title"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["title"], "verbose_name_plural": "Products"},
        ),
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True,
                help_text="Code-barres (optionnel, pour la douchette)",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="final_value",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="prix_achat",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Prix d'achat unitaire (pour la traçabilité)",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="value",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gte", 0)), name="product_value_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_value__gte", 0)),
                name="product_discount_value_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("final_value__gte", 0)),
                name="product_final_value_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("prix_achat__gte", 0)),
                name="product_prix_achat_gte_0",
            ),
        ),
    ]
