# Generated by Django 5.2.4 on 2026-10-05 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_legacy_data"),
        ("product", "0005_saas_1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="qty",
        ),
        migrations.AlterField(
            model_name="category",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="accounts.account",
            ),
        ),
    ]
