# Generated by Django 5.2.4 on 2026-10-05 11:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("ENTREE", "Entrée (Approvisionnement)"),
                            ("SORTIE_VENTE", "Sortie (Vente)"),
                            ("SORTIE_PERTE", "Sortie (Perte/Casse)"),
                            ("AJUSTEMENT_PLUS", "Ajustement +"),
                            ("AJUSTEMENT_MOINS", "Ajustement -"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantite",
                    models.IntegerField(
                        help_text="Quantité (positive pour entrée, négative pour sortie)"
                    ),
                ),
                (
                    "stock_avant",
                    models.PositiveIntegerField(help_text="Stock avant le mouvement"),
                ),
                (
                    "stock_apres",
                    models.PositiveIntegerField(help_text="Stock après le mouvement"),
                ),
                (
                    "prix_achat_unitaire",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Prix d'achat unitaire (pour les entrées)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "cout_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Coût total du mouvement",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Description du mouvement", max_length=200
                    ),
                ),
                (
                    "date_mouvement",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Mouvement de Stock",
                "verbose_name_plural": "Mouvements de Stock",
                "ordering": ["-date_mouvement", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TypeDepense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex: Approvisionnement, Matériel, Main d'œuvre",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description du type de dépense"
                    ),
                ),
                (
                    "couleur",
                    models.CharField(
                        default="#007bff",
                        help_text="Couleur hex pour l'affichage",
                        max_length=7,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Type de Dépense",
                "verbose_name_plural": "Types de Dépenses",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Depense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "description",
                    models.CharField(
                        help_text="Description de la dépense", max_length=200
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant de la dépense",
                        max_digits=14,
                    ),
                ),
                (
                    "date_depense",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        help_text="Date de la dépense",
                    ),
                ),
                (
                    "fournisseur",
                    models.CharField(
                        blank=True,
                        help_text="Nom du fournisseur (optionnel)",
                        max_length=150,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de facture ou référence",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notes additionnelles"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dépense",
                "verbose_name_plural": "Dépenses",
                "ordering": ["-date_depense", "-created_at"],
            },
        ),
    ]
