# Generated by Django 5.2.4 on 2026-10-05 11:13

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("aprovision", "0001_initial"),
        ("order", "0001_initial"),
        ("product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="depense",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="depense",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                help_text="Vide : dépense commune à toutes les boutiques",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="accounts.shop",
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mouvements",
                to="product.product",
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="reference_commande",
            field=models.ForeignKey(
                blank=True,
                help_text="Commande associée (pour les ventes)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="order.order",
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="reference_depense",
            field=models.ForeignKey(
                blank=True,
                help_text="Dépense associée (pour les approvisionnements)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="aprovision.depense",
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="accounts.shop",
            ),
        ),
        migrations.AddField(
            model_name="typedepense",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_types",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="depense",
            name="type_depense",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="depenses",
                to="aprovision.typedepense",
            ),
        ),
        migrations.AddConstraint(
            model_name="mouvementstock",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "stock_apres",
                        django.db.models.expressions.CombinedExpression(
                            models.F("stock_avant"), "+", models.F("quantite")
                        ),
                    )
                ),
                name="mouvement_stock_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="typedepense",
            constraint=models.UniqueConstraint(
                fields=("account", "nom"), name="typedepense_unique_nom_per_account"
            ),
        ),
        migrations.AddConstraint(
            model_name="depense",
            constraint=models.CheckConstraint(
                condition=models.Q(("montant__gt", 0)), name="depense_montant_gt_0"
            ),
        ),
    ]
