# Generated by Django 5.2.4 on 2026-10-02 15:05

import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aprovision", "0003_sync_fields"),
        ("order", "0005_alter_order_options_alter_payment_options_and_more"),
        ("product", "0003_alter_category_options_alter_product_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mouvementstock",
            options={
                "ordering": ["-date_mouvement", "-id"],
                "verbose_name": "Mouvement de Stock",
                "verbose_name_plural": "Mouvements de Stock",
            },
        ),
        migrations.AlterField(
            model_name="depense",
            name="date_depense",
            field=models.DateField(
                default=django.utils.timezone.localdate, help_text="Date de la dépense"
            ),
        ),
        migrations.AlterField(
            model_name="depense",
            name="montant",
            field=models.DecimalField(
                decimal_places=2, help_text="Montant de la dépense", max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="mouvementstock",
            name="cout_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Coût total du mouvement",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mouvementstock",
            name="prix_achat_unitaire",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Prix d'achat unitaire (pour les entrées)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="depense",
            constraint=models.CheckConstraint(
                condition=models.Q(("montant__gt", 0)), name="depense_montant_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="mouvementstock",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "stock_apres",
                        django.db.models.expressions.CombinedExpression(
                            models.F("stock_avant"), "+", models.F("quantite")
                        ),
                    )
                ),
                name="mouvement_stock_coherent",
            ),
        ),
    ]
