# Generated by Django 5.2.4 on 2026-10-05 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("aprovision", "0004_alter_mouvementstock_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="depense",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="depense",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                help_text="Vide : dépense commune à toutes les boutiques",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="accounts.shop",
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="shop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="accounts.shop",
            ),
        ),
        migrations.AddField(
            model_name="typedepense",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_types",
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="typedepense",
            name="nom",
            field=models.CharField(
                help_text="Ex: Approvisionnement, Matériel, Main d'œuvre",
                max_length=100,
            ),
        ),
        migrations.AddConstraint(
            model_name="typedepense",
            constraint=models.UniqueConstraint(
                fields=("account", "nom"), name="typedepense_unique_nom_per_account"
            ),
        ),
    ]
