# Generated by Django 5.2.4 on 2026-10-05 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_legacy_data"),
        ("aprovision", "0005_saas_1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depense",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="mouvementstock",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="accounts.shop",
            ),
        ),
        migrations.AlterField(
            model_name="typedepense",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_types",
                to="accounts.account",
            ),
        ),
    ]
