# Generated by Django 5.2.4 on 2026-04-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('wave', 'Wave'), ('mobile', 'Mobile Money'), ('bank', 'Virement bancaire'), ('credit', 'Crédit'), ('other', 'Autre')], default='cash', help_text='Méthode de paiement', max_length=50),
        ),
    ]
