# Generated by Django 5.2.4 on 2026-04-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('wave', 'Wave'), ('mobile', 'Mobile Money'), ('card', 'Carte bancaire'), ('bank', 'Virement bancaire'), ('credit', 'Crédit'), ('other', 'Autre')], default='cash', help_text='Méthode de paiement', max_length=50),
        ),
    ]
