# Generated by Django 5.2.4 on 2026-10-02 15:05

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_alter_client_options_alter_client_phone"),
        ("order", "0004_sync_fields"),
        ("product", "0003_alter_category_options_alter_product_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="order",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Somme des paiements",
                max_digits=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Vendeur",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Prix d'achat unitaire au moment de la vente",
                max_digits=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Client (obligatoire pour une vente à crédit)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="client.client",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="order",
            name="final_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total à payer",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="order",
            name="title",
            field=models.CharField(
                blank=True, help_text="Numéro de vente (V-000123)", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Sous-total des lignes",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="discount_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Prix promo au moment de la vente",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="final_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Prix unitaire appliqué",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Prix normal au moment de la vente",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="qty × final_price",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate, help_text="Date du paiement"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Espèces"),
                    ("mobile", "Mobile Money"),
                    ("card", "Carte"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="note",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["date"], name="order_order_date_74350b_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["is_paid"], name="order_order_is_paid_874d58_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gte", 0)), name="order_value_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount__gte", 0)), name="order_discount_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount__lte", models.F("value"))),
                name="order_discount_lte_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "final_value",
                        django.db.models.expressions.CombinedExpression(
                            models.F("value"), "-", models.F("discount")
                        ),
                    )
                ),
                name="order_final_value_eq",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_paid__gte", 0)),
                name="order_amount_paid_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_paid__lte", models.F("final_value"))),
                name="order_amount_paid_lte_final",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("amount_paid", models.F("final_value")), ("is_paid", True)
                    ),
                    models.Q(
                        ("amount_paid__lt", models.F("final_value")), ("is_paid", False)
                    ),
                    _connector="OR",
                ),
                name="order_is_paid_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "product"), name="orderitem_unique_product_per_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty__gte", 1)), name="orderitem_qty_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("final_price__gte", 0)),
                name="orderitem_final_price_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_price__gte", 0)),
                name="orderitem_total_price_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="payment_amount_gt_0"
            ),
        ),
    ]
