# Generated by Django 5.2.4 on 2026-10-05 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("client", "0004_saas_1"),
        ("order", "0005_alter_order_options_alter_payment_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="accounts.shop",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="title",
            field=models.CharField(
                blank=True, help_text="Numéro de vente (KAL-000123)", max_length=150
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("shop", "title"), name="order_unique_title_per_shop"
            ),
        ),
    ]
