# Generated by Django 5.2.4 on 2026-10-05 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_legacy_data"),
        ("order", "0006_saas_1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="accounts.shop",
            ),
        ),
    ]
